import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          50: "215 100% 97%",
          100: "215 100% 94%",
          500: "215 100% 50%",
          600: "215 89% 47%",
          700: "215 84% 42%",
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        success: {
          50: "138 76% 97%",
          100: "140 84% 92%",
          500: "142 71% 45%",
          600: "142 76% 36%",
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
        },
        warning: {
          50: "55 92% 95%",
          100: "55 97% 88%",
          500: "45 93% 47%",
          600: "43 96% 56%",
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
        },
        danger: {
          50: "0 86% 97%",
          100: "0 93% 94%",
          500: "0 84% 60%",
          600: "0 84% 60%",
          DEFAULT: "var(--danger)",
          foreground: "var(--danger-foreground)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
        inter: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        "fade-in": {
          "0%": {
            opacity: "0",
            transform: "translateY(10px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
        "slide-up": {
          "0%": {
            opacity: "0",
            transform: "translateY(20px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-in-out",
        "slide-up": "slide-up 0.3s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  safelist: [
    "bg-primary-50",
    "bg-primary-100",
    "bg-primary-500",
    "bg-primary-600",
    "bg-primary-700",
    "text-primary-50",
    "text-primary-100",
    "text-primary-500",
    "text-primary-600",
    "text-primary-700",
    "bg-success-50",
    "bg-success-100",
    "bg-success-500",
    "bg-success-600",
    "text-success-50",
    "text-success-100",
    "text-success-500",
    "text-success-600",
    "bg-warning-50",
    "bg-warning-100",
    "bg-warning-500",
    "bg-warning-600",
    "text-warning-50",
    "text-warning-100",
    "text-warning-500",
    "text-warning-600",
    "bg-danger-50",
    "bg-danger-100",
    "bg-danger-500",
    "bg-danger-600",
    "text-danger-50",
    "text-danger-100",
    "text-danger-500",
    "text-danger-600",
    "bg-blue-100",
    "text-blue-800",
    "bg-green-100",
    "text-green-800",
    "bg-purple-100",
    "text-purple-800",
    "bg-orange-100",
    "text-orange-800",
    "bg-yellow-100",
    "text-yellow-800",
    "bg-red-100",
    "text-red-800",
    "bg-pink-100",
    "text-pink-800",
    "bg-indigo-100",
    "text-indigo-800",
    "bg-gray-100",
    "text-gray-800",
  ],
} satisfies Config;
